default_chain: STRIDE-TESTNET-2
memo: gauthui02#5267
chains:
  GAIA:
    key: gaia-icq
    chain-id: GAIA
    rpc-addr: http://95.216.21.32:23657
    grpc-addr: http://95.216.21.32:23090
    account-prefix: cosmos
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1uatom
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
    memo-prefix: gauthui02#5267
  STRIDE-TESTNET-2:
    key: stride-icq
    chain-id: STRIDE-TESTNET-2
    rpc-addr: http://localhost:20657
    grpc-addr: http://localhost:20090
    account-prefix: stride
    keyring-backend: test
    gas-adjustment: 1.2
    gas-prices: 1ustrd
    key-directory: /root/.icq/keys
    debug: false
    timeout: 20s
    block-timeout: ""
    output-format: json
    sign-mode: direct
    memo-prefix: gauthui02#5267
cl: {}
